-- Junão Store — suporte/tickets + chat em tempo real
-- Projeto atual: esta estrutura já foi aplicada no Supabase.
-- Use este arquivo apenas ao instalar o projeto em outro banco.

create table if not exists public.suporte_tickets (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  discord text not null,
  cliente_nome text not null default '',
  assunto text not null,
  pedido_id text null references public.pedidos(id) on delete set null,
  status text not null default 'aberto' check (status in ('aberto','em_atendimento','aguardando_cliente','fechado')),
  prioridade text not null default 'normal' check (prioridade in ('baixa','normal','alta','urgente')),
  responsavel_id uuid null references public.perfis(id) on delete set null,
  realtime_token uuid not null default gen_random_uuid() unique,
  nao_lidas_equipe integer not null default 0 check (nao_lidas_equipe >= 0),
  nao_lidas_cliente integer not null default 0 check (nao_lidas_cliente >= 0),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  ultima_mensagem_em timestamptz not null default now(),
  fechado_em timestamptz null
);

create table if not exists public.suporte_mensagens (
  id bigint generated by default as identity primary key,
  ticket_id uuid not null references public.suporte_tickets(id) on delete cascade,
  autor_tipo text not null check (autor_tipo in ('cliente','colaborador','sistema')),
  autor_id uuid null references public.perfis(id) on delete set null,
  autor_nome text not null default '',
  mensagem text not null check (char_length(mensagem) between 1 and 4000),
  criado_em timestamptz not null default now()
);

create index if not exists suporte_tickets_discord_idx on public.suporte_tickets (lower(discord));
create index if not exists suporte_tickets_status_ultima_idx on public.suporte_tickets (status, ultima_mensagem_em desc);
create index if not exists suporte_mensagens_ticket_criado_idx on public.suporte_mensagens (ticket_id, criado_em asc, id asc);

alter table public.suporte_tickets enable row level security;
alter table public.suporte_mensagens enable row level security;
revoke all on table public.suporte_tickets from anon;
revoke all on table public.suporte_mensagens from anon;
grant select on table public.suporte_tickets to authenticated;
grant select on table public.suporte_mensagens to authenticated;

drop policy if exists suporte_tickets_equipe_ler on public.suporte_tickets;
create policy suporte_tickets_equipe_ler on public.suporte_tickets
  for select to authenticated using (public.eh_equipe());

drop policy if exists suporte_mensagens_equipe_ler on public.suporte_mensagens;
create policy suporte_mensagens_equipe_ler on public.suporte_mensagens
  for select to authenticated using (public.eh_equipe());

create or replace function public.cliente_suporte_tickets(p_discord text, p_codigo text)
returns table (
  id uuid, numero bigint, assunto text, pedido_id text, status text, prioridade text,
  realtime_token uuid, nao_lidas_cliente integer, criado_em timestamptz,
  atualizado_em timestamptz, ultima_mensagem_em timestamptz, responsavel_nome text
)
language plpgsql stable security definer set search_path = ''
as $$
declare d text;
begin
  select c.discord into d
  from public.clientes c
  where lower(trim(c.discord)) = lower(trim(p_discord))
    and upper(trim(c.codigo)) = upper(trim(replace(p_codigo,' ','')))
    and coalesce(c.status,'ativo') <> 'inativo'
  limit 1;
  if d is null then return; end if;

  return query
  select t.id,t.numero,t.assunto,t.pedido_id,t.status,t.prioridade,t.realtime_token,
         t.nao_lidas_cliente,t.criado_em,t.atualizado_em,t.ultima_mensagem_em,
         coalesce(p.nome,'')::text
  from public.suporte_tickets t
  left join public.perfis p on p.id=t.responsavel_id
  where lower(trim(t.discord))=lower(trim(d))
  order by t.ultima_mensagem_em desc,t.numero desc;
end; $$;
revoke all on function public.cliente_suporte_tickets(text,text) from public;
grant execute on function public.cliente_suporte_tickets(text,text) to anon,authenticated;

create or replace function public.cliente_suporte_mensagens(p_discord text,p_codigo text,p_ticket_id uuid)
returns table (id bigint,ticket_id uuid,autor_tipo text,autor_nome text,mensagem text,criado_em timestamptz)
language plpgsql stable security definer set search_path = ''
as $$
declare d text;
begin
  select c.discord into d
  from public.clientes c
  where lower(trim(c.discord))=lower(trim(p_discord))
    and upper(trim(c.codigo))=upper(trim(replace(p_codigo,' ','')))
    and coalesce(c.status,'ativo')<>'inativo'
  limit 1;
  if d is null then return; end if;
  if not exists(
    select 1 from public.suporte_tickets t
    where t.id=p_ticket_id and lower(trim(t.discord))=lower(trim(d))
  ) then return; end if;

  return query
  select m.id,m.ticket_id,m.autor_tipo,m.autor_nome,m.mensagem,m.criado_em
  from public.suporte_mensagens m
  where m.ticket_id=p_ticket_id
  order by m.criado_em asc,m.id asc;
end; $$;
revoke all on function public.cliente_suporte_mensagens(text,text,uuid) from public;
grant execute on function public.cliente_suporte_mensagens(text,text,uuid) to anon,authenticated;

create or replace function public.cliente_suporte_abrir(
  p_discord text,p_codigo text,p_assunto text,p_mensagem text,p_pedido_id text default null
)
returns table (id uuid,numero bigint,realtime_token uuid)
language plpgsql volatile security definer set search_path = ''
as $$
declare
  c_rec record;
  t public.suporte_tickets;
  m public.suporte_mensagens;
  assunto_limpo text:=trim(coalesce(p_assunto,''));
  msg_limpa text:=trim(coalesce(p_mensagem,''));
begin
  select c.discord,c.nome into c_rec
  from public.clientes c
  where lower(trim(c.discord))=lower(trim(p_discord))
    and upper(trim(c.codigo))=upper(trim(replace(p_codigo,' ','')))
    and coalesce(c.status,'ativo')<>'inativo'
  limit 1;
  if c_rec.discord is null then raise exception 'Acesso do cliente inválido.'; end if;
  if char_length(assunto_limpo)<3 or char_length(assunto_limpo)>120 then
    raise exception 'O assunto precisa ter entre 3 e 120 caracteres.';
  end if;
  if char_length(msg_limpa)<1 or char_length(msg_limpa)>4000 then
    raise exception 'A mensagem precisa ter entre 1 e 4000 caracteres.';
  end if;
  if p_pedido_id is not null and not exists(
    select 1 from public.pedidos p
    where p.id=p_pedido_id and lower(trim(coalesce(p.discord,'')))=lower(trim(c_rec.discord))
  ) then raise exception 'Esse pedido não pertence ao cliente.'; end if;

  insert into public.suporte_tickets(
    discord,cliente_nome,assunto,pedido_id,status,prioridade,
    nao_lidas_equipe,nao_lidas_cliente,ultima_mensagem_em
  ) values(
    c_rec.discord,coalesce(c_rec.nome,''),assunto_limpo,p_pedido_id,
    'aberto','normal',1,0,now()
  ) returning * into t;

  insert into public.suporte_mensagens(ticket_id,autor_tipo,autor_id,autor_nome,mensagem)
  values(t.id,'cliente',null,coalesce(c_rec.nome,c_rec.discord),msg_limpa)
  returning * into m;

  perform realtime.send(
    jsonb_build_object(
      'ticket_id',t.id,'message_id',m.id,'autor_tipo',m.autor_tipo,
      'autor_nome',m.autor_nome,'mensagem',m.mensagem,'criado_em',m.criado_em,'status',t.status
    ),
    'mensagem','suporte:'||t.realtime_token::text,false
  );

  return query select t.id,t.numero,t.realtime_token;
end; $$;
revoke all on function public.cliente_suporte_abrir(text,text,text,text,text) from public;
grant execute on function public.cliente_suporte_abrir(text,text,text,text,text) to anon,authenticated;

create or replace function public.suporte_enviar_mensagem(
  p_ticket_id uuid,p_mensagem text,p_discord text default null,p_codigo text default null
)
returns table (id bigint,ticket_id uuid,autor_tipo text,autor_nome text,mensagem text,criado_em timestamptz,status text)
language plpgsql volatile security definer set search_path = ''
as $$
declare
  t public.suporte_tickets;
  m public.suporte_mensagens;
  c_rec record;
  perfil_rec record;
  tipo text;
  nome text;
  uid uuid;
  status_novo text;
  msg_limpa text:=trim(coalesce(p_mensagem,''));
begin
  if char_length(msg_limpa)<1 or char_length(msg_limpa)>4000 then
    raise exception 'A mensagem precisa ter entre 1 e 4000 caracteres.';
  end if;

  select * into t from public.suporte_tickets st where st.id=p_ticket_id for update;
  if not found then raise exception 'Ticket não encontrado.'; end if;
  if t.status='fechado' then raise exception 'Este ticket está fechado.'; end if;

  uid:=auth.uid();
  if uid is not null and public.eh_equipe() then
    select p.nome into perfil_rec from public.perfis p
    where p.id=uid and p.ativo=true limit 1;
    if perfil_rec.nome is null then raise exception 'Colaborador sem acesso.'; end if;
    tipo:='colaborador';
    nome:=perfil_rec.nome;
    status_novo:='aguardando_cliente';
  else
    select c.discord,c.nome into c_rec
    from public.clientes c
    where lower(trim(c.discord))=lower(trim(p_discord))
      and upper(trim(c.codigo))=upper(trim(replace(p_codigo,' ','')))
      and coalesce(c.status,'ativo')<>'inativo'
    limit 1;
    if c_rec.discord is null or lower(trim(c_rec.discord))<>lower(trim(t.discord)) then
      raise exception 'Acesso do cliente inválido.';
    end if;
    tipo:='cliente';
    nome:=coalesce(c_rec.nome,c_rec.discord);
    uid:=null;
    status_novo:='em_atendimento';
  end if;

  insert into public.suporte_mensagens(ticket_id,autor_tipo,autor_id,autor_nome,mensagem)
  values(t.id,tipo,uid,nome,msg_limpa)
  returning * into m;

  if tipo='colaborador' then
    update public.suporte_tickets
    set status=status_novo,
        responsavel_id=coalesce(responsavel_id,auth.uid()),
        nao_lidas_cliente=nao_lidas_cliente+1,
        nao_lidas_equipe=0,
        atualizado_em=now(),
        ultima_mensagem_em=m.criado_em,
        fechado_em=null
    where suporte_tickets.id=t.id
    returning * into t;
  else
    update public.suporte_tickets
    set status=status_novo,
        nao_lidas_equipe=nao_lidas_equipe+1,
        nao_lidas_cliente=0,
        atualizado_em=now(),
        ultima_mensagem_em=m.criado_em,
        fechado_em=null
    where suporte_tickets.id=t.id
    returning * into t;
  end if;

  perform realtime.send(
    jsonb_build_object(
      'ticket_id',t.id,'message_id',m.id,'autor_tipo',m.autor_tipo,
      'autor_nome',m.autor_nome,'mensagem',m.mensagem,'criado_em',m.criado_em,'status',t.status
    ),
    'mensagem','suporte:'||t.realtime_token::text,false
  );

  return query select m.id,m.ticket_id,m.autor_tipo,m.autor_nome,m.mensagem,m.criado_em,t.status;
end; $$;
revoke all on function public.suporte_enviar_mensagem(uuid,text,text,text) from public;
grant execute on function public.suporte_enviar_mensagem(uuid,text,text,text) to anon,authenticated;

create or replace function public.suporte_marcar_lido(
  p_ticket_id uuid,p_discord text default null,p_codigo text default null
)
returns boolean language plpgsql volatile security definer set search_path = ''
as $$
declare t public.suporte_tickets; d text;
begin
  select * into t from public.suporte_tickets st where st.id=p_ticket_id;
  if not found then return false; end if;

  if auth.uid() is not null and public.eh_equipe() then
    update public.suporte_tickets set nao_lidas_equipe=0 where suporte_tickets.id=p_ticket_id;
    return true;
  end if;

  select c.discord into d
  from public.clientes c
  where lower(trim(c.discord))=lower(trim(p_discord))
    and upper(trim(c.codigo))=upper(trim(replace(p_codigo,' ','')))
    and coalesce(c.status,'ativo')<>'inativo'
  limit 1;
  if d is null or lower(trim(d))<>lower(trim(t.discord)) then return false; end if;

  update public.suporte_tickets set nao_lidas_cliente=0 where suporte_tickets.id=p_ticket_id;
  return true;
end; $$;
revoke all on function public.suporte_marcar_lido(uuid,text,text) from public;
grant execute on function public.suporte_marcar_lido(uuid,text,text) to anon,authenticated;

create or replace function public.suporte_mudar_status(p_ticket_id uuid,p_status text)
returns boolean language plpgsql volatile security definer set search_path = ''
as $$
declare t public.suporte_tickets; s text:=lower(trim(coalesce(p_status,'')));
begin
  if auth.uid() is null or not public.eh_equipe() then raise exception 'Sem permissão.'; end if;
  if s not in ('aberto','em_atendimento','aguardando_cliente','fechado') then
    raise exception 'Status inválido.';
  end if;

  update public.suporte_tickets
  set status=s,
      responsavel_id=case when s in ('em_atendimento','aguardando_cliente') then coalesce(responsavel_id,auth.uid()) else responsavel_id end,
      fechado_em=case when s='fechado' then now() else null end,
      atualizado_em=now()
  where suporte_tickets.id=p_ticket_id
  returning * into t;

  if not found then return false; end if;

  perform realtime.send(
    jsonb_build_object('ticket_id',t.id,'status',t.status,'atualizado_em',t.atualizado_em),
    'ticket','suporte:'||t.realtime_token::text,false
  );
  return true;
end; $$;
revoke all on function public.suporte_mudar_status(uuid,text) from public;
revoke execute on function public.suporte_mudar_status(uuid,text) from anon;
grant execute on function public.suporte_mudar_status(uuid,text) to authenticated;

do $$ begin
  if not exists(
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='suporte_tickets'
  ) then
    alter publication supabase_realtime add table public.suporte_tickets;
  end if;
end $$;
